# Base tagging rules
# Example tag_rules.yaml
mandatory_rules:
  global:
    - key: Environment
      allowed_values: ["Production::PROD", "Non-production::DEV","Non-production::PLAB" ,"Non-production::QAT"]
      suggestion: "Environment classification"

    - key: Application
      allowed_values: ["JP"]
      case_insensitive: true
      suggestion: "Main application name"
      
    - key: Owner
      allowed_values: ["jayantapaul.jp18@gmail.com"]
      suggestion: "Team responsible for the resource"
    
  aws_s3_bucket:
    - key: DataRetention
      allowed_values: ["30d", "1y", "5y"]
      suggestion: "Data retention policy"
      
    - key: Sensitivity
      allowed_values: ["public", "confidential", "restricted"]
      case_insensitive: true
      suggestion: "Data sensitivity level"

    # - key: DataRetention
    #   allowed_values:  # Explicit list
    #     - "30 Days"
    #     - "1 Year"
    #     - "5 Years"
    #   suggestion: "Data retention policy"

optional_tags:
  - key: CostCenter
    suggestion: "Financial tracking code"
    
  - key: Terraform
    allowed_values: ["true", "false"]
    case_insensitive: true
    suggestion: "Mark Terraform-managed resources"

excluded_resources:
  - aws_iam_role
  - aws_iam_policy
  - aws_s3_bucket_versioning
  - aws_s3_bucket_ownership_controls
  - aws_s3_bucket_acl